// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/attendance-dashboard/Aurora.tsx": () => import("../components/mockups/attendance-dashboard/Aurora.tsx"),
  "./components/mockups/attendance-dashboard/BoldModern.tsx": () => import("../components/mockups/attendance-dashboard/BoldModern.tsx"),
  "./components/mockups/attendance-dashboard/CleanLight.tsx": () => import("../components/mockups/attendance-dashboard/CleanLight.tsx"),
  "./components/mockups/attendance-dashboard/DarkPro.tsx": () => import("../components/mockups/attendance-dashboard/DarkPro.tsx"),
  "./components/mockups/attendance-dashboard/SlatePro.tsx": () => import("../components/mockups/attendance-dashboard/SlatePro.tsx")
};
